config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'recipes#index' #para que o heroku reconheça a página inicial
  resources :recipes do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :name, :rating, :comment, presence: true
  validates_length_of :comment, maximum: 50

  RATING = [0,1,2,3,4,5]
  validates_inclusion_of :rating, in: RATING
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, :stuff, :duration, :prepare_mode, presence:true
    validates_length_of :stuff, maximum: 200
    validates_length_of :prepare_mode, maximum: 600
    validates_numericality_of :calories, greather_than_or_equal_to:0, presence:true
    validates_format_of :poster, allow_blank:true, with:  /\w+\.(gif|jpeg|png)\z/i, message:" utilizar somente arquivos GIF,JPEG ou PNG."
    
    KIND = %w(Carnes Aves Peixes Massas Saladas Doces)
    validates_inclusion_of :kind , in: KIND

    has_many :comments , dependent: :destroy

    def light?
        calories <= 100
    end

    def self.created_at
        where('created_at <= ?', Time.now ).order('created_at desc')
        
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true,
                    format: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/,
                    uniqueness: {case_sensitive: false}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_recipe

    def index
        @comments = @recipe.comments
    end

    def new
        @comment = @recipe.comments.new
    end

    def create
        @comment = @recipe.comments.new(comment_params)
        if @comment.save
            redirect_to recipe_comments_path(@recipe), notice: 'Comentário gravado com sucesso!'
        else
            render :new
        end
            
    end

    private

        def comment_params
            params.require(:comment).permit(:name, :comment, :rating)
        end

        def set_recipe
            @recipe = Recipe.find(params[:recipe_id])
        end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    
    def index
        @recipes = Recipe.created_at
    end

    def show
        @recipe = Recipe.find(params[:id])        
    end

    def edit
        @recipe = Recipe.find(params[:id])
    end

    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.update(recipe_params)
            redirect_to @recipe, notice: "Receita atualizada com sucesso!"
        else
            render :edit
        end
    end
    
    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            redirect_to @recipe, notice: "Receita criada com sucesso!"
        else
            render :new
        end
    end
    
    def destroy
        @recipe = Recipe.find(params[:id])
        @recipe.destroy
        redirect_to recipes_url, alert: "Receita apagada com sucesso!"
    end
    
    private
        def recipe_params
            recipe_params = params.require(:recipe).permit(:name, :stuff, :calories, :prepare_mode, :cost, :kind, :portion, :duration, :poster)
        end
        
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

    def formata_caloria(recipe)
        if recipe.light?
            content_tag(:strong, "Esta é uma receita light")
        else
            recipe.calories
        end
    end

    def imagem(recipe)
        if recipe.poster.blank?
            image_tag('no-photo.png')
        else
            image_tag(recipe.poster)            
        end
        
    end
    
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for([@recipe, @comment]) do |f| %>
    <%= render 'layouts/errors', object: @comment %>
    <p class="form-group">
        <%= f.label :Nome %><br/>
        <%= f.text_field :name, autofocus: true, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Estrelas %><br/>
        <%= f.select :rating, Comment::RATING , prompt: 'Escolha a quantidade de estrelas', class:"form-control"%>
    </p>
    <p class="form-group">
        <%= f.label :Comentário %><br/>
        <%= f.text_area :comment, placeholder:"Escreva seu comentário ..." ,class:"form-control" %>
    </p>
    <p>
        <%= f.submit class:'btn btn-outline-info' %>
        <%= link_to 'Cancelar', root_path , class: 'btn btn-outline-danger'%>
    </p>
<% end %>

app/views/comments/index.html.erb
<div class="float-right d-block mb-5">
    <%= link_to recipes_path, class:'btn btn-outline-info' do %>
        <i class="fas fa-home"> <span>Voltar para receitas</span></i>
    <% end %>
</div>
<div class="clearfix"></div>
<% if @recipe.comments.size > 0 %>
    <% @comments.each do |comment| %>
        <div class="card mb-3">
            <div class="card-header">
                <h3><%= comment.name %></h3> 
                <small class="small_font_rating"> 
                    <% pluralize(comment.rating, 'estrela', 'estrelas') %>
                </small>
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    <small class="small_font">
                        - <%= time_ago_in_words(comment.created_at) %>
                    </small> 
                    escreveu:
                </h5>
                <p class="card-text"><%= comment.comment %></p>
            </div>
        </div>
    <% end %>
<% else %>
    <div class="card mb-5">
        <div class="card-header">
            <h1>Sem comentários!?</h1>
        </div>
        <div class="card-body">
            <h5 class="card-title">Seja o primeiro a comentar sobre esta receita! ;)</h5>
        </div>
    </div>
<% end %>
<div class="clearfix"></div>
<div class="float-right d-block mt-5">
    <%= link_to recipes_path, class:'btn btn-outline-info' do %>
        <i class="fas fa-home"> <span>Voltar para receitas</span></i>
    <% end %>
</div>

app/views/comments/new.html.erb
<div class="card">
    <div class="card-header">
        <h2>Criando novo Comentário</h2>
    </div>
    <div class="card-body">
        <%= render 'form' %>
    </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger" role="alert">
        <ul>
            <% object.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
    <div class='container'>
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span ariahidden="true">×</span></button>
            <%= flash[:notice] %>
        </div>
    </div>
    <% elsif flash[:alert] %>
    <div class='container'>
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span ariahidden="true">×</span></button>
            <%= flash[:alert] %>
        </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="clearfix"></div>
<footer  class="footer mt-5">
    <div class="container">
        <p class="text-muted text-center">Developed by singulare.me</p>
    </div>
</footer>

app/views/layouts/_header.html.erb
  <header class="mb-5">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
          <%= link_to image_tag('logo.png',  :class=>'img-fluid', size: '200', alt:'Página inicial'), root_path, class: 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Receitas Online</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
  </head>
  <body>
    <%= render 'layouts/header' %>
      <%= render 'layouts/flash' %>
      <div class="container">
          <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
    <%= render 'layouts/errors', object: @recipe %>
    <p class="form-group">
        <%= f.label :Imagem %>
        <%= f.text_field :poster, placeholder: ".gif, .jpeg, .png", class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Nome %>
        <%= f.text_field :name, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Ingredientes %>
        <%= f.text_area :stuff, cols: 20, rows: 5, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Tipo %>
        <%= f.select :kind, Recipe::KIND , prompt: 'Escolha uma opção', class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Calorias %>
        <%= f.number_field :calories, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Modo_de_Preparo %>
        <%= f.text_area :prepare_mode, cols: 20, rows: 5, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Tempo_de_Preparo %>
        <%= f.time_select :duration, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Porções %>
        <%= f.text_field :portion, class:"form-control" %>
    </p>
    <p class="form-group">
        <%= f.label :Custo %>
        <%= f.number_field :cost, class:"form-control" %>
    </p>
    <p class="form-group">
    <%= f.submit "Salvar receita", class:"btn btn-outline-success" %>
    <%= link_to "Cancelar alterações", root_path, class:"btn btn-outline-danger" %>
    </p>
<% end %>

app/views/recipes/edit.html.erb
<div class="card">
  <div class="card-header">
    <h1>Editando Receitas</h1>
  </div>
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="row mt-5">
    <div class="col-lg-12">
        <h1 class="page-header"><%= pluralize(@recipes.size, 'Receita','Receitas') %>
            <small class="float-right btn btn-outline-danger">
                <%= link_to "Nova Receita", new_recipe_path %>
            </small>
        </h1>
    </div>
</div>
<div class="row listaReceitasImg">
    <% @recipes.each do |recipe| %>
        <div class="col-xs-12 col-sm-4 col-md-3">
            <div class="card">
                <%= link_to imagem(recipe), recipe %>
                <div class="card-body">
                    <h4 class="card-title"><%= link_to recipe.name , recipe %></h4>
                    <p class="card-text"><%= truncate(recipe.stuff, lenght: 15 , separator: '') %></p>
                    <h5>Calorias:</h5>
                    <p><%= formata_caloria(recipe) %></p>
                    <h5>Tempo de preparo:</h5>
                    <p><%= recipe.duration.to_formatted_s(:time) %></p>
                    <h5>Custo:</h5>
                    <p><%= number_to_currency(recipe.cost) %></p>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/recipes/new.html.erb
<div class="card">
  <div class="card-header">
    <h1>Inserir uma nova Receita</h1>
  </div>
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="jumbotron">
    <article>
    <header class="listaReceitasImg">
        <%= imagem(@recipe) %>
        <h1><%= @recipe.name %></h1>
    </header>
    <h2>Tipo</h2>
    <p><%= @recipe.kind %></p>
    <h2>Ingredientes</h2>
    <p><%= @recipe.stuff %></p>
    <h2>Calorias</h2>
    <p><%= @recipe.calories %></p>
    <h2>Modo de Preparo</h2>
    <p><%= @recipe.prepare_mode %></p>
    <h2>Tempo de Preparo</h2>
    <p><%= @recipe.duration.to_formatted_s(:time) %> minutos</p>
    <h2>Porções</h2>
    <p><%= pluralize(@recipe.portion, 'porção', 'porções') %></p>
    <h2>Custo</h2>
    <p><%= number_to_currency(@recipe.cost) %></p>
</article>
<%= link_to pluralize(@recipe.comments.size, 'Comentário', 'Comentários'), recipe_comments_path(@recipe) %>
<%= link_to 'Novo comentário', new_recipe_comment_path(@recipe), class: 'btn btn-outline-primary' %>
</div>
<nav>
    <%= link_to recipes_path, class:'btn btn-outline-info' do %>
        <i class="fas fa-home"> <span>Receitas</span></i>
    <% end %>
    <%= link_to edit_recipe_path(@recipe), class:'btn btn-outline-success' do %>
        <i class="fas fa-pencil-alt"> <span>Editar Receita</span></i>
    <% end %>
    <%= link_to recipe_path(@recipe), method: :delete, data:{ confirm: "Deseja realmente deletar esta receita?" }, class:'btn btn-outline-danger' do %>
        <i class="fas fa-trash-alt"> <span>Deletar Receita</span></i>
    <% end %>
</nav>